version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build  # This will clean and transpile code to 'dist-server'
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
